---
- name: Print Showroom namespace information
  ansible.builtin.debug:
    msg: "Setting up showroom in namespace {{ _showroom_namespace }}"

- name: Setup Namespace
  ansible.builtin.include_tasks: setup-namespace.yaml

- name: Render helm chart with values
  environment:
    KUBECONFIG: "{{ _showroom_kubeconfig | default(omit) }}"
  kubernetes.core.helm_template:
    chart_repo_url: "{{ ocp4_workload_showroom_chart_package_url }}"
    chart_ref: "{{ ocp4_workload_showroom_deployer_chart_name }}"
    chart_version: "{{ ocp4_workload_showroom_deployer_chart_version }}"
    release_name: "{{ ocp4_workload_showroom_name }}"
    release_namespace: "{{ _showroom_namespace }}"
    release_values:
      deployment:
        target: "{{ ocp4_workload_showroom_deployment_target }}"
        hostname: "{{ _deployer_domain }}"
        guid: "{{ guid }}"
        namespace: "{{ _showroom_namespace }}"
        createNamespace: "{{ ocp4_workload_showroom_deployment_create_namespace }}"

      layout_name: "{{ ocp4_workload_showroom_layout_name }}"

      layout: "{{ ocp4_workload_showroom_layout }}"

      services:
        content:
          repoUrl: "{{ ocp4_workload_showroom_services_content_git_repo }}"
          repoRef: "{{ ocp4_workload_showroom_content_git_repo_ref }}"
          antoraPlaybook: "{{ ocp4_workload_showroom_services_content_antora_playbook }}"
          data: "{{ _showroom_vars | to_nice_yaml(width=1337, default_style='\"') }}"
        terminal:
          enable: {{ ocp4_workload_showroom_services_terminal_enable }}
          command: "{{ ocp4_workload_showroom_services_terminal_command }}"
          terminal_command: "{{ ocp4_workload_showroom_services_terminal_terminal_command }}"
        terminal2:
          enable: {{ ocp4_workload_showroom_services_terminal2_enable }}
          command: "{{ ocp4_workload_showroom_services_terminal2_command }}"
          terminal_command: "{{ ocp4_workload_showroom_services_terminal2_terminal_command }}"
        terminal3:
          enable: {{ ocp4_workload_showroom_services_terminal3_enable }}
          command: "{{ ocp4_workload_showroom_services_terminal3_command }}"
          terminal_command: "{{ ocp4_workload_showroom_services_terminal3_terminal_command }}"

        helloworld:
          enable: {{ ocp4_workload_showroom_services_helloworld_enable }}

  register: r_helm_templates

- name: Deploy rendered manifests to OpenShift
  kubernetes.core.k8s:
    kubeconfig: "{{ _showroom_kubeconfig | default(omit) }}"
    definition: "{{ r_helm_templates.stdout | from_yaml_all }}"

# - name: Report Variables
#   ansible.builtin.include_tasks: report-variables.yaml
