---
- name: Print Showroom namespace information
  ansible.builtin.debug:
    msg: "Setting up showroom in namespace {{ _showroom_namespace }}"

- name: Setup Namespace
  ansible.builtin.include_tasks: setup-namespace.yaml

- name: Render helm chart with values
  environment:
    KUBECONFIG: "{{ _showroom_kubeconfig | default(omit) }}"
  kubernetes.core.helm_template:
    chart_repo_url: "{{ ocp4_workload_showroom_chart_package_url }}"
    chart_ref: "{{ ocp4_workload_showroom_deployer_chart_name }}"
    chart_version: "{{ ocp4_workload_showroom_deployer_chart_version }}"
    release_name: "{{ ocp4_workload_showroom_name }}"
    release_namespace: "{{ _showroom_namespace }}"
    release_values:
      deployment:
        target: "{{ ocp4_workload_showroom_deployment_target }}"
        hostname: "{{ _deployer_domain }}"
        guid: "{{ guid }}"
        namespace: "{{ _showroom_namespace }}"
        createNamespace: "{{ ocp4_workload_showroom_deployment_create_namespace }}"

      layout_name: "{{ ocp4_workload_showroom_layout_name }}"

      layout: "{{ ocp4_workload_showroom_layout }}"

      services:
        content:
          repoUrl: "{{ ocp4_workload_showroom_services_content_git_repo }}"
          repoRef: "{{ ocp4_workload_showroom_content_git_repo_ref }}"
          antoraPlaybook: "{{ ocp4_workload_showroom_services_content_antora_playbook }}"
          data: "{{ _showroom_vars | to_nice_yaml(width=1337, default_style='\"') }}"
        terminal:
          enable: "{{ ocp4_workload_showroom_services_terminal_enable }}"
          sshMethod: "{{ ocp4_workload_showroom_services_terminal_ssh_method }}"

          host: "{{ _showroom_user_data.bastion_public_hostname }}"
          user: "{{ _showroom_user_data['users'][_showroom_user].bastion_ssh_user_name | default(_showroom_user_data.bastion_ssh_user_name) }}"
          pass: "{{ _showroom_user_data['users'][_showroom_user].bastion_ssh_password | default(_showroom_user_data.bastion_ssh_password) }}"
          port: "{{ _showroom_user_data.bastion_ssh_port | default(22) }}"

        helloworld:
          enable: "{{ ocp4_workload_showroom_services_helloworld_enable }}"

  register: r_helm_templates

- name: Deploy rendered manifests to OpenShift
  kubernetes.core.k8s:
    kubeconfig: "{{ _showroom_kubeconfig | default(omit) }}"
    definition: "{{ r_helm_templates.stdout | from_yaml_all }}"

# - name: Report Variables
#   ansible.builtin.include_tasks: report-variables.yaml
